# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd

# Load the raw data
raw_data = pd.read_csv("raw_data.csv")

# Data cleaning and preprocessing
# For example, remove duplicates
cleaned_data = raw_data.drop_duplicates()

# Convert grip strength from pounds to kilograms
cleaned_data['Grip strength (kg)'] = cleaned_data['Grip strength'] * 0.453592

# Save the cleaned data
cleaned_data.to_csv("cleaned_data.csv", index=False)